#!/usr/bin/perl -w
#
use strict;
use warnings;

my $type = shift @ARGV || die "ERROR: change_inst_type <type>\n";
my $inst = shift @ARGV || `get_instance`;
system( "stop_inst ${inst}" );
system( "aws ec2 modify-instance-attribute --instance-type ${type} --instance-id ${inst}" );
