#!/usr/bin/perl -w
#
use strict;
use warnings;

my $count  = shift @ARGV || die "ERROR: create_insts <cnt>\n";
my $type   = shift @ARGV || `inst_type`;
my $image  = shift @ARGV || `owner_image`;
my $key    = shift @ARGV || `inst_key`;
my $group  = shift @ARGV || `owner_group`;
my $region = shift @ARGV || `owner_region`;
system( "aws ec2 run-instances --image-id ${image} --count ${count} --instance-type ${type} --key-name ${key} --security-group-ids ${group} --region ${region}" );
