#!/usr/bin/perl -w
#
use strict;
use warnings;

my $group  = shift @ARGV || `my_group`;
my $region = shift @ARGV || `my_region`;
system( "aws ec2 describe-security-groups --group-id ${group} --region ${region} --output json" );
