#!/usr/bin/perl -w
#
use strict;
use warnings;

my $snapshot = shift @ARGV || die "image_snapshot snapshot-id name\n";
my $name     = shift @ARGV || die "image_snapshot snapshot-id name\n";
my $inst     = shift @ARGV || `master_inst`;
my $arch     = shift @ARGV || `image_arch`;
my $device   = `inst_device ${inst}`;
system( "aws ec2 register-image --name ${name} --architecture ${arch} --virtualization-type hvm --root-device-name ${device} --block-device-mappings DeviceName=\"${device}\",Ebs={DeleteOnTermination=true,SnapshotId=\"${snapshot}}\"" );

my $image = `my_last_image`;
print "Waiting for ${image} to be in the 'available' state...\n";
for( ;; )
{
    my $state = `aws ec2 describe-images --image-ids ${image} --query 'Images[*].State'`;
    chomp $state;
    $state eq "available" and last;
    sleep 1;
}
