#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `master_inst`;
my $device = `aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].[BlockDeviceMappings[*].[DeviceName]]' --output text`;
chomp $device;
print $device;
