#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `master_inst`;
my $zone = `aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].Placement.AvailabilityZone' --output text`; 
chomp $zone;
print $zone;
