#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `master_inst`;
my $owner = `aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].NetworkInterfaces[*].SubnetId' --output text`; print $owner;
