#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `get_instance`;
my $key = `aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].[KeyName]' --output text`;
chomp $key;
print $key;
