#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `get_instance`;
my $host =`aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].[PublicDnsName]' --output text`;
chomp $host;
print $host;
