#!/usr/bin/perl -w
#
use strict;
use warnings;

my $name = shift @ARGV || die "ERROR: install <name>\n";
my $inst = shift @ARGV || `get_instance`;
system( "start_inst ${inst}" );
my $host =`aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].[PublicDnsName]' --output text`;
chomp $host;
my $key = `inst_key $inst`;
system( "ssh -i ~/.ssh/${key}.pem ec2-user\@${host} 'rm -fr lambda-${name}; mkdir lambda-${name}'" );
system( "zip -r index.zip *" );
system( "scp -i ~/.ssh/${key}.pem ${name}.create index.zip ec2-user\@${host}:lambda-${name}/" );
system( "ssh -i ~/.ssh/${key}.pem ec2-user\@${host} 'cd lambda-${name}; ./${name}.create'" );
#system( "stop_inst" );
