#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `get_instance`;
my $state = `aws ec2 describe-instances --instance-ids ${inst} --query 'Reservations[*].Instances[*].State.Name' --output text`;
chomp $state;
print $state;
