#!/usr/bin/env python3
#
import os
import sys
import subprocess

cmd_en = True

def die( msg ):
    print( f'ERROR: {msg}' )
    sys.exit( 1 )

def cmd( c, echo=True, echo_stdout=False, can_die=True ):
    if echo: print( c )
    if cmd_en:
        info = subprocess.run( c, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT )
        if echo_stdout: print( info.stdout )
        if can_die and info.returncode != 0: die( f'command failed: {c}' )
        return info.stdout
    else:
        return ''

def get_script_dir():
    script_path = sys.argv[0]
    abs_script_path = os.path.abspath( script_path )
    return os.path.dirname( abs_script_path )

bundle     = 'bundle'
inst_cnt   = 1
do_launch  = True
do_harvest = True

i = 1
while i < len(sys.argv):
    arg = sys.argv[i]
    i += 1
    if   arg == '-b':
        bundle = sys.argv[i]
    elif arg == '-c': 
        inst_cnt = int(sys.argv[i])
    elif arg == '-do_launch':
        do_launch = int(sys.argv[i]) == 1
    elif arg == '-do_harvest':
        do_harvest = int(sys.argv[i]) == 1
    else:
        die( f'unknown option: {arg}' )
    i += 1

bundle_tar_path = f'{bundle}.tar.gz'
if not os.path.exists( bundle_tar_path ): 
    die( f'bundle {bundle_tar_path} not found, use -b <bundle> switch to change bundle prefix' )

if do_launch:
    print( f'Removing local results files...' )
    cmd( f'rm -f results*.out results*.tar.gz' )

    print( f'Copying {bundle_tar_path} to master instance in fresh ./run dir...' )
    cmd( f'on_inst "rm -fr ./run; mkdir -p ./run"' )
    cmd( f'to_inst {bundle_tar_path} ./run/{bundle_tar_path}' )

    print( f'Untaring and building bundle on master instance under ./run dir...' )
    cmd( f'on_inst "cd ./run; tar xvfz {bundle_tar_path}; ./build.sh"' )

    print( f'Launching {inst_cnt} instances that are clones of the master instance...' )
    script = get_script_dir() + '/run_run_sh'
    cmd( f'create_insts {inst_cnt} -script {script} -clone_master' )
else:
    print( f'NOT relaunching work' )

if do_harvest:
    print( f'Harvesting results...' )
    image = cmd( 'my_image', echo=False, echo_stdout=True )
    while True:
        # get list of all instances that use image
        s = cmd( f'my_insts -image {image} -show_state', echo=False, echo_stdout=True )
        lines = s.rstrip( '\n' ).splitlines()

        # for each one in the stopped state, figure out its index, copy
        # and the stdout and results.tar.gz file to this PC. Then delete the instance.
        num_left = 0
        for line in lines:
            fields = line.split()
            name = fields[0]
            state = fields[1]
            if state == 'stopped':
                print( f'Harvesting instance {name}...' )
                cmd( f'rm -f index.out' )
                cmd( f'fm_inst {name} run/index.out index.out' )
                i = cmd( f'cat index.out', echo=False, echo_stdout=True )
                i = int(i)
                print( f'launch index: {i}' )
                print( f'Copying results{i}.out and results{i}.tar.gz...' )
                cmd( f'rm -f results{i}.out results{i}.tar.gz' )
                cmd( f'fm_inst {name} run/results.out results{i}.out' )
                print( f'Note: not currently looking for "PASS" in results{i}.out' )
                cmd( f'fm_inst {name} run/results.tar.gz results{i}.tar.gz', can_die=True )
                print( f'Deleting instance {name}...' )
                cmd( f'delete_inst {name}' )
            elif state == 'pending' or state == 'running' or state == 'stopping':
                num_left += 1

        if num_left == 0:
            print( 'Done harvesting results' )
            break

        print( f'Sleeping for 60 seconds because {num_left} instances are not done yet' )
        sleep( 60 )
            
else:
    print( f'NOT harvesting results' )
