#!/usr/bin/perl
#
use strict;
use warnings;

my $arch = "x86_64";

while( @ARGV != 0 ) 
{
    my $arg = shift @ARGV;
    if ( $arg eq "-arch" ) {
        $arch = (shift @ARGV);
    } else {
        die "ERROR: unknown linux2_images option '$arg'\n";
    }
}

system( "aws ec2 describe-images --owners amazon --filters 'Name=name,Values=amzn2-ami-hvm-2.0.????????.?-${arch}-gp2' 'Name=state,Values=available' --query 'Images[*].{ID:ImageId,Time:CreationDate}' --output text | sort -r -k 2,2" );
