#!/usr/bin/perl -w
#
use strict;
use warnings;

my $cmd = join( " ", @ARGV );

system( "start_inst" );
my $host = `inst_host`;
my $key  = `inst_key`;
system( "ssh -i ~/.ssh/${key}.pem -o 'StrictHostKeyChecking no' ec2-user\@${host} ${cmd}" );
