#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = (@ARGV != 0 && ($ARGV[0] =~ /^i-/)) ? (shift @ARGV) : `master_inst`; 
my $cmd = join( " ", @ARGV );

system( "start_inst ${inst}" );
my $host = `inst_host ${inst}`;
my $key  = `inst_key ${inst}`;
system( "ssh -i ~/.ssh/${key}.pem -o 'StrictHostKeyChecking no' ec2-user\@${host} ${cmd}" );
