#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = (@ARGV != 0 && ($ARGV[0] =~ /^i-/)) ? (shift @ARGV) : `master_inst`; 
my $username = "ec2-user";
while( @ARGV != 0 && $ARGV[0] =~ /^\-/ ) 
{
    my $arg = shift @ARGV;
    if ( $arg eq "-as" ) {
        $username = shift @ARGV;
    } else {
        die "ERROR: unknown on_inst option '$arg'\n";
    }
}
my $cmd = join( " ", @ARGV );

system( "start_inst ${inst}" );
my $host = `inst_host ${inst}`;
my $key  = `inst_key ${inst}`;
system( "ssh -i ~/.ssh/${key}.pem -o 'StrictHostKeyChecking no' ${username}\@${host} ${cmd}" );
