#!/bin/bash
echo "in run_run_sh"
sudo -u ec2-user -i <<'EOF'
cd ./run
pwd
rm -f index.out results.out
ec2-metadata -l | sed 's/.*: //' > index.out
./run.sh `cat index.out` >& results.out
EOF
shutdown
