#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = shift @ARGV || `master_inst`;
system( "stop_inst ${inst}" );
my $vol = `inst_vol ${inst}`;
system( "aws ec2 create-snapshot --volume-id ${vol}" );
my $snapshot = `vol_snapshot ${vol}`;
print "Waiting for ${snapshot} to be in the 'completed' state...\n";
for( ;; )
{
    my $state = `aws ec2 describe-snapshots --snapshot-ids ${snapshot} --query 'Snapshots[*].State'`;
    chomp $state;
    $state eq "completed" and last;
    print "state is ${state}\n";
    sleep 1;
}
