#!/usr/bin/perl -w
#
use strict;
use warnings;

my $inst = (@ARGV != 0 && ($ARGV[0] =~ /^i-/)) ? (shift @ARGV) : `master_inst`; 
my $src = shift @ARGV;
my $dst = shift @ARGV;

system( "start_inst ${inst}" );
my $host = `inst_host ${inst}`;
my $key  = `inst_key ${inst}`;
system( "scp -r -i ~/.ssh/${key}.pem -o 'StrictHostKeyChecking no' ${src} ec2-user\@${host}:${dst}" );
