#!/usr/bin/perl -w
#
use strict;
use warnings;

my $dst  = pop @ARGV;
my $srcs = join( " ", @ARGV );

system( "start_inst" );
my $host = `inst_host`;
my $key  = `inst_key`;
system( "scp -i ~/.ssh/${key}.pem ${srcs} ec2-user\@${host}:${dst}" );
