#!/usr/bin/perl -w
#
use strict;
use warnings;

my $src = join( " ", @ARGV );
my $dst = pop @ARGV;

system( "start_inst" );
my $host = `inst_host`;
my $key  = `inst_key`;
system( "scp -r -i ~/.ssh/${key}.pem ${src} ec2-user\@${host}:${dst}" );
